// Generated by CoffeeScript 1.6.3
var Hardboiled, Q, dir, fs, jsdom, path, request, urlparser, vm, _,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Q = require('q');

fs = require('fs');

urlparser = require('url');

request = require('request');

vm = require('vm');

jsdom = require('jsdom');

path = require('path');

dir = require('node-dir');

_ = require('underscore');

Hardboiled = {};

Hardboiled.Engines = require('./engines');

Hardboiled.Clue = (function() {
  function Clue(options) {
    this.runTest = __bind(this.runTest, this);
    this.test_javascript = __bind(this.test_javascript, this);
    this.test_sudo = __bind(this.test_sudo, this);
    this.test_global = __bind(this.test_global, this);
    this.test_filename = __bind(this.test_filename, this);
    this.test_domain = __bind(this.test_domain, this);
    this.test_meta = __bind(this.test_meta, this);
    this.processResult = __bind(this.processResult, this);
    this.runTests = __bind(this.runTests, this);
    this.toMatch = __bind(this.toMatch, this);
    var content, data, sandbox;
    if (options.path) {
      content = fs.readFileSync(options.path, 'utf8');
      sandbox = {};
      vm.runInNewContext('var data = ' + content, sandbox);
      data = sandbox.data;
    }
    this.data = options.data || data;
    this.tests = data.tests;
  }

  Clue.prototype.toMatch = function() {
    return {
      title: this.data.title,
      description: this.data.description,
      url: this.data.url
    };
  };

  Clue.prototype.runTests = function(page) {
    var _this = this;
    return Q.all(this.tests.map(function(test) {
      return _this['test_' + test.type].call(_this, page, test.test);
    }));
  };

  Clue.prototype.processResult = function(type, result) {
    var response;
    response = {
      type: type,
      passed: !!result && !(result instanceof Array && result.length === 0)
    };
    if (result !== !!result) {
      if (result instanceof Array) {
        response.data = {
          matches: result
        };
      } else {
        response.data = result;
      }
    }
    return response;
  };

  Clue.prototype.test_meta = function(page, data) {
    var _this = this;
    return this.runTest(data, function(d) {
      var response, result;
      result = page.hasMeta(data);
      response = _this.processResult('meta', result);
      return d.resolve(response);
    });
  };

  Clue.prototype.test_domain = function(page, regex) {
    var _this = this;
    return this.runTest(regex, function(d) {
      var response, results;
      results = regex.exec(urlparser.parse(page.url).hostname);
      response = _this.processResult('domain', !!results);
      return d.resolve(response);
    });
  };

  Clue.prototype.test_filename = function(page, filename) {
    var _this = this;
    return this.runTest(filename, function(d) {
      var response, results;
      results = page.resources.filter(function(resource) {
        return resource.isNamed(filename);
      }).map(function(resource) {
        return resource.url;
      });
      response = _this.processResult('filename', results);
      return d.resolve(response);
    });
  };

  Clue.prototype.test_selector = function(page, selector) {
    var _this = this;
    return this.runTest(selector, function(d) {
      var promise;
      promise = page.evaluate_with_args(function(selector) {
        return document.querySelector(selector) !== null;
      }, selector);
      return Q(promise).then(function(value) {
        var response;
        response = _this.processResult('selector', !!value);
        return d.resolve(response);
      });
    });
  };

  Clue.prototype.test_global = function(page, global) {
    var _this = this;
    return this.runTest(global, function(d) {
      var promise;
      promise = page.evaluate_with_args(function(variable) {
        return window[variable] !== void 0 && window[variable] !== null;
      }, global);
      return Q(promise).then(function(result) {
        var response;
        response = _this.processResult('global', !!result);
        return d.resolve(response);
      });
    });
  };

  Clue.prototype.test_sudo = function(page, fn) {
    var _this = this;
    return this.runTest(fn, function(d) {
      var response, result;
      result = fn.call(_this, page);
      response = _this.processResult('sudo', result);
      return d.resolve(response);
    });
  };

  Clue.prototype.test_javascript = function(page, fn) {
    var _this = this;
    return this.runTest(fn, function(d) {
      var promise;
      promise = page.evaluate(fn);
      return Q(promise).then(function(result) {
        var response;
        response = _this.processResult('javascript', result);
        return d.resolve(response);
      });
    });
  };

  Clue.prototype.runTest = function(test, fn) {
    var d,
      _this = this;
    d = Q.defer();
    process.nextTick(function() {
      if (!test) {
        return d.resolve(false);
      }
      return fn(d);
    });
    return d.promise;
  };

  return Clue;

})();

Hardboiled.Resource = (function() {
  function Resource(response) {
    var pieces, url_pieces;
    this.url = response.url;
    this.body = response.body;
    this.headers = response.headers;
    this.path = urlparser.parse(this.url).pathname;
    url_pieces = this.path.split('/');
    this.filename = url_pieces[url_pieces.length - 1];
    this.cleaned_name = this.filename.replace(/([-.](min|compressed))?(\.[a-z]*)?$/, '');
    this.cleaned_url = this.url.replace(/.(min|compressed)/, '');
    pieces = this.filename.split('.');
    if (pieces.length > 1) {
      this.extension = pieces[pieces.length - 1];
    }
    this.type = this.findType();
    this.comments = this.findComments();
  }

  Resource.prototype.findType = function() {
    return this.extension;
  };

  Resource.prototype.findComments = function() {
    var regex;
    if (!this.body) {
      return [];
    }
    if (this.type === 'css') {
      regex = new RegExp(/\/\*\*(.|\n)+?\*\//g);
      return this.body.match(this.comment_regex) || [];
    } else if (this.type === 'js') {
      regex = new RegExp(/\/\*[^*]*\*+([^/*][^*]*\*+)*\//g);
      return this.body.match(this.comment_regex) || [];
    }
  };

  Resource.prototype.isNamed = function(name) {
    if (name instanceof RegExp) {
      return name.test(this.cleaned_url);
    } else if (name.indexOf('/') !== -1) {
      return this.cleaned_url.indexOf(name) !== -1;
    } else {
      return name === this.cleaned_name || name === this.filename + '.' + this.extension;
    }
  };

  return Resource;

})();

Hardboiled.Page = (function() {
  function Page(options) {
    this.url = options.url;
    this.body = options.body;
    this.resources = [];
    this.meta = [];
    this.matches = [];
    this.engine = new Hardboiled.Engines[options.engine || 'PhantomJS'](this, options);
  }

  Page.prototype.processClues = function(clues) {
    var _this = this;
    return Q.all(clues.map(function(clue) {
      var d;
      d = Q.defer();
      process.nextTick(function() {
        return clue.runTests(_this).then(function(results) {
          var data, match, passed;
          passed = results.filter(function(result) {
            return result && result.passed;
          });
          if (passed.length > 0) {
            match = clue.toMatch();
            data = _.pluck(passed, 'data');
            match.data = _.compact(data);
            _this.matches.push(match);
          }
          return d.resolve();
        });
      });
      return d.promise;
    }));
  };

  Page.prototype.addResource = function(data) {
    var resource;
    resource = new Hardboiled.Resource(data);
    return this.resources.push(resource);
  };

  Page.prototype.addMeta = function(data) {
    return this.meta.push(data);
  };

  Page.prototype.hasMeta = function(data) {
    var keys,
      _this = this;
    keys = Object.keys(data);
    return this.meta.filter(function(tag) {
      var key, _i, _len;
      for (_i = 0, _len = keys.length; _i < _len; _i++) {
        key = keys[_i];
        if (data[key] instanceof RegExp) {
          if (!data[key].test(tag[key])) {
            return false;
          }
        } else {
          if (tag[key] !== data[key]) {
            return false;
          }
        }
      }
      return true;
    });
  };

  Page.prototype.evaluate_with_args = function(fn, arg1) {
    return this.engine.evaluate_with_args(fn, arg1);
  };

  Page.prototype.evaluate = function(fn) {
    return this.engine.evaluate(fn);
  };

  Page.prototype.openPage = function() {
    return this.engine.openPage();
  };

  Page.prototype.closePage = function() {
    return this.engine.closePage();
  };

  return Page;

})();

Hardboiled.Scanner = (function() {
  function Scanner(options) {
    this.path = options.path || '../clues';
  }

  Scanner.prototype.importClues = function(callback) {
    var _this = this;
    this.clues = [];
    return dir.files(path.resolve(__dirname, this.path), function(err, files) {
      var clue, file, _i, _len;
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        clue = new Hardboiled.Clue({
          path: file
        });
        _this.clues.push(clue);
      }
      return callback();
    });
  };

  Scanner.prototype.scan = function(options, callback) {
    var page,
      _this = this;
    if (!this.clues) {
      return this.importClues(function() {
        return _this.scan(options, callback);
      });
    }
    page = new Hardboiled.Page(options);
    return page.openPage().then(function() {
      return page.processClues(_this.clues);
    }).then(function() {
      page.closePage();
      return callback(null, page);
    });
  };

  return Scanner;

})();

Hardboiled.scan = function(url, callback) {
  var scanner;
  scanner = new Hardboiled.Scanner({});
  return scanner.scan({
    url: url
  }, callback);
};

module.exports = Hardboiled;
